config/routes.rb
Rails.application.routes.draw do
  resources :mensagens

  root 'mensagens#index'

end

app/models/mensagem.rb
class Mensagem < ActiveRecord::Base
    validates :titulo, :corpo, :autor, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mensagens_controller.rb
class MensagensController < ApplicationController
  before_action :set_mensagem, only: [:show, :edit, :update, :destroy]

  # GET /mensagens
  # GET /mensagens.json
  def index
    @mensagens = Mensagem.all
  end

  # GET /mensagens/1
  # GET /mensagens/1.json
  def show
  end

  # GET /mensagens/new
  def new
    @mensagem = Mensagem.new
  end

  # GET /mensagens/1/edit
  def edit
  end

  # POST /mensagens
  # POST /mensagens.json
  def create
    @mensagem = Mensagem.new(mensagem_params)

    respond_to do |format|
      if @mensagem.save
        format.html { redirect_to @mensagem, notice: 'Mensagem cadastrada com sucesso!' }
        format.json { render :show, status: :created, location: @mensagem }
      else
        format.html { render :new }
        format.json { render json: @mensagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mensagens/1
  # PATCH/PUT /mensagens/1.json
  def update
    respond_to do |format|
      if @mensagem.update(mensagem_params)
        format.html { redirect_to @mensagem, notice: 'Mensagem editada com sucesso!' }
        format.json { render :show, status: :ok, location: @mensagem }
      else
        format.html { render :edit }
        format.json { render json: @mensagem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mensagens/1
  # DELETE /mensagens/1.json
  def destroy
    @mensagem.destroy
    respond_to do |format|
      format.html { redirect_to mensagens_url, notice: 'Mensagem apagada com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mensagem
      @mensagem = Mensagem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mensagem_params
      params.require(:mensagem).permit(:titulo, :corpo, :autor, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mensagens_helper.rb
module MensagensHelper
    
    def data(data)
        data.strftime("%d/%m/%Y")
    end
    
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mural de Mensagens</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
</head>
<body>

<div class="container rounded-corners">
  <%= yield %>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

app/views/mensagens/_form.html.erb
<%= bootstrap_form_for(@mensagem) do |f| %>
  <% if @mensagem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mensagem.errors.count, "problema") %> encontrados:</h2>

      <ul>
      <% @mensagem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :titulo, label: 'Título' %>
  </div>
  <div class="field">
    <%= f.text_area :corpo, label: 'Corpo' %>
  </div>
  <div class="field">
    <%= f.text_field :autor, label: 'Autor' %>
  </div>
  <div class="field">
    <%= f.text_field :email, label: 'Email' %>
  </div>
  <div class="actions">
    <%= f.submit 'Enviar' %>
  </div>
<% end %>

app/views/mensagens/_notice.html.erb
<% if notice.present? %>
  <div id="notice" class="alert alert-success" role="alert"><%= notice %></div>
<% end %>

app/views/mensagens/edit.html.erb
<div class="float-md-right">
  <div class="btn-group">
    <%= link_to 'Voltar', mensagens_path, class: 'btn btn-secondary' %>
    <%= link_to 'Detalhar', mensagem_path(@mensagem), class: 'btn btn-secondary' %>
    <%= link_to 'Excluir', @mensagem, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-secondary' %>
  </div>
</div>

<h1>Editar Mensagem</h1>

<%= render 'form' %>

app/views/mensagens/index.html.erb
<%= render partial: 'notice' %>

<div class="float-md-right">
  <%= link_to 'Nova Mensagem', new_mensagem_path, class: "btn btn-primary" %>
</div>

<h1>Mural de Mensagens</h1>

<% if @mensagens.empty? %>
  <p>Nenhuma mensagem encontrada.</p>
<% else %>
  <% @mensagens.each do |mensagem| %>
    <div class="card">
      <div class="card-header">
        <h5><%= mensagem.titulo %></h5>
      </div>
      <div class="card-body">
        <%= mensagem.corpo %>
      </div>
      <div class="card-footer">
        <div class="btn-group">
          <%= link_to 'Detalhar', mensagem, class: 'btn btn-secondary btn-sm' %>
          <%= link_to 'Editar', edit_mensagem_path(mensagem), class: 'btn btn-secondary btn-sm' %>
          <%= link_to 'Excluir', mensagem, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-secondary btn-sm' %>
        </div>
        <div class="float-md-right">
          <small>Enviada por <%= mail_to mensagem.email, mensagem.autor %> em <%= data(mensagem.created_at) %></small>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/mensagens/new.html.erb
<div class="float-md-right">
  <div class="btn-group">
    <%= link_to 'Voltar', mensagens_path, class: 'btn btn-secondary' %>
  </div>
</div>

<h1>Nova Mensagem</h1>

<%= render 'form' %>

app/views/mensagens/show.html.erb
<%= render partial: 'notice' %>

<div class="float-md-right">
  <div class="btn-group">
    <%= link_to 'Voltar', mensagens_path, class: 'btn btn-secondary' %>
    <%= link_to 'Editar', edit_mensagem_path(@mensagem), class: 'btn btn-secondary' %>
    <%= link_to 'Excluir', @mensagem, method: :delete, data: { confirm: 'Tem certeza?' }, class: 'btn btn-secondary' %>
  </div>
</div>

<h1>Detalhar Mensagem</h1>

<div class="card">
  <div class="card-header">
    <h5><%= @mensagem.titulo %></h5>
  </div>
  <div class="card-body">
    <%= @mensagem.corpo %>
  </div>
  <div class="card-footer">
    <small>Enviada por <%= mail_to @mensagem.email, @mensagem.autor %> em <%= data(@mensagem.created_at) %></small>
  </div>
</div>